// This file is auto-generated by ts2rs. Do not edit manually.
// Source: /workspaces/ts-rs/rs/test-driver/tests/resources/0003/types.ts

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Product {
    pub id: String,
    pub name: String,
    pub price: f64,
    #[serde(rename = "inStock")]
    pub in_stock: bool,
    pub categories: Vec<String>,
}
