// This file is auto-generated by ts2rs. Do not edit manually.
// Source: /workspaces/ts-rs/rs/test-driver/tests/resources/0003/types.ts

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Product {
    pub id: String,
    pub name: String,
    pub price: f64,
    #[serde(rename = "inStock")]
    pub in_stock: bool,
    pub categories: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ShoppingCart {
    pub items: Vec<Product>,
    #[serde(rename = "totalPrice")]
    pub total_price: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub discount: Option<f64>,
    pub tags: Vec<String>,
}
