// This file is auto-generated by ts2rs. Do not edit manually.
// Source: /workspaces/ts2rs/rs/test-driver/tests/resources/0024/types.ts

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Update<T> {
    pub value: Option<T>,
    pub name: String,
    pub count: f64,
    pub items: Vec<T>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<T>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SetDocumentPayload {
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "requestId")]
    pub request_id: Option<Update<f64>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "primaryHtml")]
    pub primary_html: Option<Update<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "secondaryHtml")]
    pub secondary_html: Option<Update<String>>,
}
