// This file is auto-generated by ts2rs. Do not edit manually.
// Source: /workspaces/ts2rs/rs/test-driver/tests/resources/0024/types.ts

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Update<T> {
    pub value: Option<T>,
    pub name: String,
    pub count: f64,
    pub items: Vec<T>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<T>,
}
