// This file is auto-generated by ts-to-rs. Do not edit manually.
// Source: /workspaces/ts-rs/rs/test-driver/tests/resources/0013/types.ts

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Shape {
    Circle {
        pub radius: f64,
        pub center: (f64, f64),
    },
    Rectangle {
        pub width: f64,
        pub height: f64,
    },
    Triangle {
        pub base: f64,
        pub height: f64,
    },
}
