// This file is auto-generated by ts-to-rs. Do not edit manually.
// Source: /workspaces/ts2rs/rs/test-driver/tests/resources/0019/types.ts

use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DataContainer {
    pub id: String,
    #[serde(rename = "mixedData")]
    pub mixed_data: Value,
    pub name: String,
}
