// This file is auto-generated by ts2rs. Do not edit manually.
// Source: /workspaces/ts-rs/rs/test-driver/tests/resources/0007/types.ts

use serde::{Deserialize, Serialize};
use std::collections::{HashMap};
use serde_json::Value;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct EmptyCollections {
    #[serde(rename = "emptyStringArray")]
    pub empty_string_array: Vec<String>,
    #[serde(rename = "emptyNumberArray")]
    pub empty_number_array: Vec<f64>,
    #[serde(rename = "emptyRecord")]
    pub empty_record: HashMap<String, Value>,
}
