// This file is auto-generated by ts2rs. Do not edit manually.
// Source: /workspaces/ts-rs/rs/test-driver/tests/resources/0007/types.ts

use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OptionalFields {
    #[serde(rename = "requiredString")]
    pub required_string: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "optionalString")]
    pub optional_string: Option<String>,
    #[serde(rename = "requiredNumber")]
    pub required_number: f64,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "optionalNumber")]
    pub optional_number: Option<f64>,
    #[serde(rename = "emptyArray")]
    pub empty_array: Vec<Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "optionalArray")]
    pub optional_array: Option<Vec<String>>,
    #[serde(rename = "nullableField")]
    pub nullable_field: Option<String>,
}
