// This file is auto-generated by ts-to-rs. Do not edit manually.
// Source: /workspaces/ts-rs/rs/reverse-test-driver/tests/resources/0001/types.ts

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Person {
    pub name: String,
    pub age: f64,
    pub email: String,
}
