// This file is auto-generated by ts2rs. Do not edit manually.
// Source: /workspaces/ts-rs/rs/test-driver/tests/resources/0009/types.ts

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "pending")]
    Pending,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "rejected")]
    Rejected,
    #[serde(rename = "cancelled")]
    Cancelled,
}
