// This file is auto-generated by ts2rs. Do not edit manually.
// Source: /workspaces/ts2rs/rs/test-driver/tests/resources/0026/types.ts

use serde::{Deserialize, Serialize};
use std::collections::{HashMap};
use serde_json::Value;

/// A span within text content, represented as [start, end] character offsets
pub type TextSpan = (f64, f64);

/// A weighted span within text content
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WeightedSpan {
    pub span: TextSpan,
    pub opacity: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SyncEntry {
    pub id: f64,
    /// Weighted span in the primary (first) element
    pub one: WeightedSpan,
    /// Weighted spans in the secondary (second) element (one-to-many)
    pub many: Vec<WeightedSpan>,
    /// Optional color override as [r, g, b]. If not provided, a color from the palette is used.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub color: Option<(f64, f64, f64)>,
    /// Optional metadata associated with this entry (e.g. alignment explanation).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<HashMap<String, Value>>,
    /// When true, arrows on connection lines point from many → one.
/// When false, arrows point from one → many.
/// When null, no arrows are drawn.
    #[serde(rename = "arrowToOne")]
    pub arrow_to_one: Option<bool>,
}
